# Write your MySQL query statement below
SELECT DISTINCT
    A.ID
FROM
    WEATHER A
LEFT JOIN
    WEATHER B
ON TRUE
    AND A.RECORDDATE = B.RECORDDATE + INTERVAL 1 DAY
WHERE
    A.TEMPERATURE > B.TEMPERATURE;