# Write your MySQL query statement below
SELECT DISTINCT
    USER_ID as BUYER_ID,
    JOIN_DATE,
    SUM(CASE WHEN YEAR(O.ORDER_DATE) = 2019 THEN 1 ELSE 0 END) OVER (PARTITION BY USER_ID) AS ORDERS_IN_2019
FROM
    USERS U
JOIN
    ORDERS O
ON U.USER_ID = O.BUYER_ID;